soyuz-machine-id: ENC[AES256_GCM,data:larPvAjU+Ruj1tX2YZjEH7Sfg7M4UFwdReouO1k5T+I=,iv:FZxV1jbnLFW/L15MK7theqinVfnO0iPoM05TqzqSNsM=,tag:xTil3ArYUkUQrtv0Ckh3EQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15yahwftet0jdz6mpy8lxk26sx27xdmdkwawseqst9dqskt8aw54q8w2qvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVVZ1Q3NsQzc5R0xaL0NK
            R3JvYXY5YjQwcnNnTmtPSzE1QnVtcjBMR0hNCnpIbkFaVCtDcnVwQ1gxM3hsZm0r
            aFVYQVVXZ1lBdnoxeW8vT1YyOHpSbjQKLS0tIHFUSE5WcS9zcTNvQTEzdURWQjhF
            M1NZUlo0d1VlaXRKT25VSFh5OE8rdncKuaIAxID7Uw9+Wcre5uslVoSwKctGhB9g
            uce63DUSRow2Q2lYAYkkYoX2ZSdaUQZbNcstaiFamRxGsXJFTIVI3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T01:45:05Z"
    mac: ENC[AES256_GCM,data:JZ8zBBWUbufd4bFKaI/IFOX0p+E7YW0xDrZZJXAJfK9WlyNYpHF0Cs3R//UGNrpEL7qUM5kMiWDKtBuMiG9VNk+L/MFaUUKzHAfmAMM3l+Z6gC6SmoXXAjCdwGojSyPFd7lyIAl0Kym3UvHOpZHDq4nf4U4PG/hvLC1iIDfjnOs=,iv:s86z1XJ8sr4DzpJsMgquYwT4WptUf9KylHVkQAWP06A=,tag:lUByy1olW0ghuj6onHmZkA==,type:str]
    pgp:
        - created_at: "2024-01-03T01:44:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DsCy9fF9008oSAQdAcpZjWi8AsUegb1HG0tM8B+A6zo+c/atuMV53g7g7aggw
            rnDZSxBIs7JbgqHdD1ir5ohhNiBlVHQCrmY+mEbjgWuwgvNoodhAC+pvkOGKPo3M
            1GgBCQIQLRxNdr+ZJI34JJ7iKYi5a26dLTRMJMIxJRFHPluKGHOKCx3MkX+OwhmX
            pToPR6gsDqaGvDk/N6Xs/69hd483NKeBYNy5L6emv1k6j4J1JWEQiU5Cxi/tTJon
            PiZfu+pqYBlHfA==
            =jq05
            -----END PGP MESSAGE-----
          fp: 308155094625A2F5BA83D78EC1FEBB4FA9C3AC52
    unencrypted_suffix: _unencrypted
    version: 3.8.1
