keys:
  - &users
    - &rui 308155094625A2F5BA83D78EC1FEBB4FA9C3AC52
  - &hosts
    - &saturn age1a40ey3fn7lcpddpztqduduc5zz5wmdk7gmk0hvpt8n8eehay2cusf2vr3g

creation_rules:
  - path_regex: hosts/saturn/secrets.ya?ml$
    key_groups:
      - age:
          - *saturn
        pgp: *users
