keys:
  - &users
    - &rui 308155094625A2F5BA83D78EC1FEBB4FA9C3AC52
  - &hosts
    - &soyuz age15yahwftet0jdz6mpy8lxk26sx27xdmdkwawseqst9dqskt8aw54q8w2qvj
    - &sputnik age1xjr8754s9qcf5u9xlhhkvxyt4gr7y49xjlalu334fswtuxew9fgsws03yz
    - &ariane age1hfwae629u7s3xsrmns6spxlghh2adrkuasmxz09yfufswgy5gf6qnka0n9

creation_rules:
  - path_regex: users/rui/secrets.ya?ml$
    key_groups:
    - age: *hosts
      pgp:
      - *rui
  - path_regex: hosts/common-secrets.ya?ml$
    key_groups:
    - age: *hosts
      pgp: *users
  - path_regex: hosts/configs/soyuz/.*secrets.ya?ml$
    key_groups:
    - age:
      - *soyuz
      pgp: *users
  - path_regex: hosts/configs/sputnik/.*secrets.ya?ml$
    key_groups:
    - age:
      - *sputnik
      pgp: *users
  - path_regex: hosts/configs/ariane/.*secrets.ya?ml$
    key_groups:
    - age:
      - *ariane
      pgp: *users