{
  home.file.".config/".text = ''
    <monitors version="2">
      <configuration>
        <logicalmonitor>
          <x>3840</x>
          <y>0</y>
          <scale>1</scale>
          <monitor>
            <monitorspec>
              <connector>DP-0</connector>
              <vendor>AOC</vendor>
              <product>24G2W1G3-</product>
              <serial>SXIP5HA009118</serial>
            </monitorspec>
            <mode>
              <width>1920</width>
              <height>1080</height>
              <rate>165.003</rate>
            </mode>
          </monitor>
        </logicalmonitor>
        <logicalmonitor>
          <x>1920</x>
          <y>0</y>
          <scale>1</scale>
          <primary>yes</primary>
          <monitor>
            <monitorspec>
              <connector>DP-2</connector>
              <vendor>AOC</vendor>
              <product>24G2W1G3-</product>
              <serial>WUBP3HA003007</serial>
            </monitorspec>
            <mode>
              <width>1920</width>
              <height>1080</height>
              <rate>165.003</rate>
            </mode>
          </monitor>
        </logicalmonitor>
        <logicalmonitor>
          <x>0</x>
          <y>0</y>
          <scale>1</scale>
          <monitor>
            <monitorspec>
              <connector>DP-4</connector>
              <vendor>AOC</vendor>
              <product>24G2W1G3-</product>
              <serial>SXIP5HA008340</serial>
            </monitorspec>
            <mode>
              <width>1920</width>
              <height>1080</height>
              <rate>165.003</rate>
            </mode>
          </monitor>
        </logicalmonitor>
      </configuration>
    </monitors>
  '';
}