keys:
  - &users
    - &rui 308155094625A2F5BA83D78EC1FEBB4FA9C3AC52
  - &hosts
    - &devbox age19atlktxfg70wnp92av7ghgevghvxwy2hkd6yfdu2ufc5wns6svmst4jh59

creation_rules:
  - path_regex: ./modules/nixos/features/[users]/rui/secrets.ya?ml$
    key_groups:
      - age: *hosts
        pgp:
          - *rui
  - path_regex: hosts/proxmox/devbox-lxc/secrets.ya?ml$
    key_groups:
      - age:
          - *devbox
        pgp: *users
