keys:
  - &users
    - &rui 308155094625A2F5BA83D78EC1FEBB4FA9C3AC52
  - &hosts
    - &devbox age1l9ceachwp0x3v3s0nl6g90upg3fqvq60x7dfmgeewef2pee2jaaqh78duk
    - &sshwifty age1xvqrklu3axts3g2t6yjzchhv44w4sa6d07r2m5ttqvyydtwy9g4sggpsn5

creation_rules:
  - path_regex: ./modules/nixos/features/[users]/rui/secrets.ya?ml$
    key_groups:
      - age: *hosts
        pgp:
          - *rui
  - path_regex: hosts/virtual-machine/devbox/secrets.ya?ml$
    key_groups:
      - age:
          - *devbox
        pgp: *users
  - path_regex: hosts/virtual-machine/sshwifty/secrets.ya?ml$
    key_groups:
      - age:
          - *sshwifty
        pgp: *users
