curseforge-api-key: ENC[AES256_GCM,data:vXAszo6xVoImLfIAlmzqe4noNf02PBKUmTPCo4EFeHpysKlaezbcIj7XU0NRn8dKXS8s3vF9bCQtz2niVl/O,iv:QSMz1bHKKyADFYCUqet7yH0WX8nr2vmrAIYeMhQfc9E=,tag:2ix3Rr6Mj+LNwKhl4iF9IA==,type:str]
firefly-tunnel-token: ENC[AES256_GCM,data:u5nkn7mEk+e0PhpUlhmNB/udh4r4zqMqp0/ZG5m0sU4m/jCZ0uQZ8qH/y999s59FslHrOvGtDES+jCQcVlk5sLxf+gXXONASYAEL8ur8Nl45gMSV8dOc8NLEc03I87zqR22lkUEHcPyWYZwaGk6Xj+HnPE3rP1h+rngyL1t5n9kx7TUolfEXjoBC6j+Db9/PUoBvTgI/WX4Mx7ha74APZqBXXjFdSuP0e6rT6gq+40H2vZu/y3oPWw==,iv:Eb2It4R2dQYq1AJbvJ4O4IB9TxeNRIup4SHbIMot9ok=,tag:MmCXwHjnmgrCQm+UwmtJQQ==,type:str]
firefly-cron-token: ENC[AES256_GCM,data:8zxSrco4LmWGO7krTdeF7ZN8eU1FMd5QcTSVPbU8/CY=,iv:9J6K/Wg3vttDBx8S1IXLCeWfRwNkOe6soEUU2v1s9zM=,tag:5Br9BNSWstaG3HRHjpm+4A==,type:str]
firefly-app-key: ENC[AES256_GCM,data:LC5mmj1VO4MsekYHWAGLWUJVlPbdk9aZLjkSUkatffI=,iv:xUGgHs60zqMnIoYBognYXy4BloehhJMiZg4AZ/EIWBg=,tag:k49SZVzKn6nuO9fGbDy6nQ==,type:str]
firefly-database-password: ENC[AES256_GCM,data:r7t3VmG64rPv+MckXlXQfNYRdF/FweaUX7JFr+jTBu8=,iv:AyBuObeLBA6yN0eYDm472S5lr4bPcg/9Y4yHvir7Glc=,tag:OtLvRiNG9VlO4NuJBkerog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xjr8754s9qcf5u9xlhhkvxyt4gr7y49xjlalu334fswtuxew9fgsws03yz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWGlUVmJ4NzRlSkEya28w
            dU1SVi9WeXdLWWZIelZ0djJsWnlMVC85RWowClFxak1oczhSZWE2ZEFZUklFdzY2
            QURSVXNiSmRIT080R3M5UXNXVlAzZFUKLS0tIGxuSzRJcCtMd28yRG9GK1JiUVNE
            Mzh4WGxoQmg5K3MxR1I5M0xJSVRmeDQKwtrINf3aX8DMvXvbl7BEXRkRiJwxmHHl
            p+6vWmEZT7I4QXfviaWh97gA1Lc/u44ycMSu6HsyaTeFpTL3BC694w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T16:45:17Z"
    mac: ENC[AES256_GCM,data:Kwv4GxX9X5DX+zH8I+WLPcgXP81r/Ocg+dv4D+LaueyCE+g7TuBnVb58OjhsaJMpv7qhV1r8sIGABOKl6CF6lx160kyxjmAat+S2BEoPkcmhiJWV6OKA1TydZtyRezfpbeYyiaekVShCtBjaGkidKBxmOfLMDO3vKxyQUJQ+82E=,iv:p8HyH66iscOBQVgs2jfu+m8GCHaMBcN6I+qfsTgK6sg=,tag:IYr+mXyF2ytWwkOb5N6g8w==,type:str]
    pgp:
        - created_at: "2024-01-16T16:08:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DsCy9fF9008oSAQdAHY4irEZJEPhTKGJlUgX2SvOfuHBh3A0RuHhWiOVb/24w
            f/CDgpBTgJUkcN5Nz71jlivCacQUpVuFtuWGfPLbHAjlGrNuBqBXGajVkeVoquqc
            1GgBCQIQ+/m7oif4ZvJWtOKJzOOvwEA6js1zdcE1uJKy1h/VQthQSgFz/KFRhXax
            yFwoAgoA5yCtT4mhrH50EVmj0xY5fwU6N0Jxb6jTXlAA7UL+vTCNeUY3Cgx+2kzp
            q8FEOPVchq7chQ==
            =54R6
            -----END PGP MESSAGE-----
          fp: 308155094625A2F5BA83D78EC1FEBB4FA9C3AC52
    unencrypted_suffix: _unencrypted
    version: 3.8.1
