ariane-machine-id: ENC[AES256_GCM,data:OKoMngR+ayPR7vpl5vjtSbt5En/G3OeBPvf9AU/8p0c=,iv:iPNKCUbD+jRYNlws0V2Tu83sdvVYkRy9cMKSWysSMSc=,tag:RkzP9IpKi5JX3fBwoLy7Cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hfwae629u7s3xsrmns6spxlghh2adrkuasmxz09yfufswgy5gf6qnka0n9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdEovYVBBd0JuK1d4aEE5
            ZVNWL09kT3k4TWRqT2xnYW1SVEJ2MWdmVVVVCnlPU2NRQ1ZrN1MyS0d1NzVBR0NG
            aEtmSVROY29VNGhNcW5nYmpVMWJUR2MKLS0tIHVDZXZtN1FHRTRRUTI2dVNnY2ZV
            dTRwV1RDMjZOUFJrSUdicEdHYjdHT2sKif9mhstyX91qc7HQt8GXvtJydiOZ4pSG
            HWEuXjwEOc3K6d23FVhS9Z2Ovz8LSIoDUxRL0Rf7MO0GhpHu5B43Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T20:50:26Z"
    mac: ENC[AES256_GCM,data:Co4l9y+f5R8EbPObglsYjl2/1tGqDGmb1dWGMC/epXmYeJr8pbLJWO7DzXAS383hG1GhNoPQ4qjM/OeqNS96CvlzP6s2oMVdtPPeRCKGtyCK6Qej71mJseGh48CVsPZpBonI8J4xRWAyTgdX4QpS1Or/WTt6GAAsELT1H7edUtw=,iv:H1EXHjERGnqr+tamOO4zD+kSXFqjtYZfQm8MC53T7qA=,tag:KUTqtylyp99mnAQrF+tJLA==,type:str]
    pgp:
        - created_at: "2024-02-08T00:12:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DsCy9fF9008oSAQdAa3h61im48hEOP51aPy/nHdhnx9c9QtL/OJgheT41T3gw
            bbIJ+my4pr1X2Si9zbBK4rHMYXFwwN/qVr+TvkLnUZU/k4jYhL81dkIl64Gath9A
            1GYBCQIQ/SKfGnSHQmlG2Emo8IIrkMWIOZw3abaY8ndkCjW9DEObwChtNAqzQpDQ
            9929ntYSypErmus8adC//f4kuJjtatjgQT9Lj8B5rheH3Bnk+KZp7UbF3e7/JZ3/
            IIpFUWNzeYE=
            =97n8
            -----END PGP MESSAGE-----
          fp: 308155094625A2F5BA83D78EC1FEBB4FA9C3AC52
    unencrypted_suffix: _unencrypted
    version: 3.8.1
